### ISSUE TITLE
Remove @react-native-community/slider dependency

### ISSUE THREAD

**Issue by BenJeau** [BenJeau/react-native-draw#1]
Remove `@react-native-community/slider` dependency by allowing users to provide their own "slider" or way to change opacity and thickness, via a component passed as a prop or with callbacks. This would make the library more lightweight

**Comment by cerven** [comment]
I'm not using "Bottom bar" at all, but have to install "slider" event it is not used

**Comment by BenJeau** [comment]
This would be accomplished by doing #21. Maybe I will be able to do it this week - although my finals for schools are coming up soon. If I'm not able to do it this week, I will for sure be able to do it in a month, when I'll be done with school.
