### ISSUE TITLE
Refactor code in Draw component

### ISSUE THREAD

**Issue by BenJeau** [BenJeau/react-native-draw#21]
Create a separation in the Draw component where users can
- Create a canvas component that has no color picker / brush properties

**Comment by hugopretorius914** [comment]
This would be amazing!

**Comment by BenJeau** [comment]
Just laying out the details:
* `@benjeau/react-native-draw` would only contain the renderer/canvas
* `@benjeau/react-native-draw-extras` would contain everything else (bottom section - color picker, brush properties, undo, delete)

Both of these dependencies will be in this repo - although I am unsure how to push to two separate npm packages with `react-native-bob`. I'm not sure when I'll do this, but I really want this do this since I already have the Skia renderer done and want to merge it with this code so bad, but I can't as of now
