### ISSUE TITLE
[iOS][Release Build]: Facing crash

### ISSUE THREAD

**Issue by KushalDesai1** [BenJeau/react-native-draw#33]
The dev build on iOS is working perfectly fine.
When I generate the release build, it crashes.

Has anyone experienced the same?

**Comment by BenJeau** [comment]
Hi, sorry I don't have access to an Apple computer to test it on iOS unfortunately, but if someone finds the source of the crash, I will happily accept a PR :)

**Comment by BenJeau** [comment]
I'm sorry that I haven't been able to produce an iOS example application.

Could you provide more information on the crash:
* Are there any logs?
* What's your version of React Native, iOS, macOS?
* On what kind of computer are you building the release?
* Are you running it on the simulator or an iOS device?

**Comment by BenJeau** [comment]
I have just built a release iOS application locally and have not faced any crashes (see image below)

<img width="1323" alt="Screen Shot 2022-02-02 at 11 54 31 PM" src="https://user-images.githubusercontent.com/22248828/152283453-5e72d629-2338-4816-b65c-2e153ae977b3.png">

Feel free to re-open if you have more information on your crash
