### ISSUE TITLE
Reexport `createSVGPath` from utils

### ISSUE THREAD

**Issue by cerven** [BenJeau/react-native-draw#34]
I am saving just coordinates of draw. When I want to show original drawing(pass `initialValues.paths`), it is not possible just passing there coordinates(and color, thickness,...), it is required pass also `path` as SVG string. This SVG string is internally generated when drawing by function in utils `createSVGPath`.

It would be good to reexport this function so it can be used for generating SVG path, or add method for generate drawing just from coordinates without SVG path variable(call createSVGPath internally).

Now I am importing this function directly with `import { createSVGPath } from "../node_modules/@benjeau/react-native-draw/src/utils";` which is not ideal

**Comment by cerven** [comment]
Even #PR35 fixes mentioned issue, still will be good to reexport this function, it can be sometimes handy. (in my app I need it again in another usecase).

Actually I need to generate SVG from points(as preview) without rendering "Draw".

My options are:
  - render Draw, get SVG and destroy Draw
  - import "createSVGPath", and copy getSVG method(https://github.com/BenJeau/react-native-draw/blob/master/src/Draw.tsx#L483)

**Comment by BenJeau** [comment]
Ok sounds good, I will re-export it

**Comment by BenJeau** [comment]
This is now available in version `0.5.0` :tada:
