### ISSUE TITLE
Move to Gesture API introduced with react-native-gesture-handler 2

### ISSUE THREAD

**Issue by gfringeli** [BenJeau/react-native-draw#54]
Currently, the gestures are handled using an older react-native-gesture-handler (RNGH) API, i.e. PanGestureHandler. Moving to the new Gesture API introduced with react-native-gesture-handler 2 would remove a warning notification popping up in the React Native app during development.
In addition, in order to be able to use the old API when having installed version 2 of RNGH in some cases requires to add the line
```
import 'react-native-gesture-handler';
```
at very beginning of `index.js` of a React Native project. There does not seem agreement in the community about the extent and the source of this issue. But using the new API resolved the issue in my case.

**Comment by BenJeau** [comment]
Changes are pushed to new version `v0.8.0` 🚀
