### ISSUE TITLE
Lock the canvas

### ISSUE THREAD

**Issue by Jun-Ikeda** [BenJeau/react-native-draw#56]
### Desired solution (feature)

Hello!
I very much appreciate you publishing such a useful library.
This library is almost perfect. But I think it would be better if I could lock the canvas and forbid editing.
Thanks.

**Comment by BenJeau** [comment]
That is for sure a useful feature to have, let me quickly make the change

**Comment by BenJeau** [comment]
There should now be a `enabled` prop for the `Canvas` component in version `v0.8.1` 🚀

**Comment by Jun-Ikeda** [comment]
Hi Benoît,
Thanks for the quick update, and I’m happy to contribute to its improvement, if not a significant contribution haha
