### ISSUE TITLE
VSCode is unable to find types

### ISSUE THREAD

**Issue by Gamez0** [BenJeau/react-native-draw#62]
### On what kind of device are you using this library?

- [X] Android
- [ ] iOS
- [ ] Web

### Environment

```markdown
- OS:Window 10
- react-native: 0.68.2
- @benjeau/react-native-draw: 0.8.1
- react: 17.0.2
- @types/react-native: 0.67.3
- typescript: 4.4.4
- @babel/core: 7.12.9
```

### Current Behavior

![image](https://user-images.githubusercontent.com/34051876/168962612-1d92445c-419a-4fff-9743-dd3266c8e954.png)

### Expected Behavior

should be able to find a declaration file for module.

### Steps To Reproduce

import CanvasRef in Typescript React Native Project with environment given above.

### Anything else?

Seems Typescript can't find declaration file in the module. 
Is't this project meant to be used in typescripts based projects?
(I've solved my issue by declaring the interfaces that I need. But definitely there's a better way to solve it)

**Comment by BenJeau** [comment]
That is weird, since the code is written in typescript and the types can be found within the `node_modules` folder

<img width="1061" alt="Screen Shot 2022-05-18 at 2 30 43 PM" src="https://user-images.githubusercontent.com/22248828/169118603-b4f15775-ed79-47da-b545-77905e7a9948.png">

I seem to have found a way to make it work - let me publish a new version with the fix

**Comment by BenJeau** [comment]
Now this should properly work on version `0.8.3` of `@benjeau/react-native-draw` and `0.2.2` of `@benjeau/react-native-draw-extras` 🚀

<img width="692" alt="Screen Shot 2022-05-18 at 3 11 53 PM" src="https://user-images.githubusercontent.com/22248828/169138088-2a39d187-a689-4ee1-a004-7844c4b03105.png">

Feel free to re-open this issue if this is not fixed for you

**Comment by Gamez0** [comment]
Hi thanks for the new version! It fixed my problem #
>
> I seem to have found a way to make it work - let me publish a new version with the fix
I was wandering if you could share what the problem was and how did you fixed it
Thanks in advance

**Comment by BenJeau** [comment]
You can see the changes here https://github.com/BenJeau/react-native-draw/commit/719f45e998f48a0753e9c596fa10952b48cce635, basically the `package.json` was not pointing to the right location for the types
