### ISSUE TITLE
Bezier curves

### ISSUE THREAD

**Issue by aidyun** [BenJeau/react-native-draw#75]
### Desired solution (feature)

I'm not sure if the program already does this, but it would be nice to have bezier curve conversion.

**Comment by sickopickle** [comment]
I used the getSvg function, and it seems that it already uses Bezier curves! This is amazing because it directly fits my applications of machine learning which require Bezier curve inputs. Kudos to whoever made the code for that. One question is why aren't there any 's's in the svg?

**Comment by sickopickle** [comment]
Also, it seems like it overfits simple lines a lot, using multiple curves when it could just be one. Can someone point towards where the code for this is, so I can modify it?
